---
version: '2.1'

services:
  redis:
    image: redis:6

  tests:
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - ./:/app/
    command:
      - make
      - tests
