checks:
  required_workflows:
    clean.yaml: False
    audit.yaml: False
    rebuild.yaml: False
  versions: False
  prospector_config:
    properties:
      doc-warnings: false

publish:
  docker:
    images: []
